In [1]:
from pydataset import data

In [2]:
import acquire

In [3]:
df_iris = data('iris')

In [4]:
df_iris

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
1             5.1          3.5           1.4          0.2      setosa
2             4.9          3.0           1.4          0.2      setosa
3             4.7          3.2           1.3          0.2      setosa
4             4.6          3.1           1.5          0.2      setosa
5             5.0          3.6           1.4          0.2      setosa
6             5.4          3.9           1.7          0.4      setosa
7             4.6          3.4           1.4          0.3      setosa
8             5.0          3.4           1.5          0.2      setosa
9             4.4          2.9           1.4          0.2      setosa
10            4.9          3.1           1.5          0.1      setosa
11            5.4          3.7           1.5          0.2      setosa
12            4.8          3.4           1.6          0.2      setosa
13            4.8          3.0           1.4          0.1      setosa
14            4.3          3.0           1.1          0.1      setosa
15            5.8          4.0           1.2          0.2      setosa
16            5.7          4.4           1.5          0.4      setosa
17            5.4          3.9           1.3          0.4      setosa
18            5.1          3.5           1.4          0.3      setosa
19            5.7          3.8           1.7          0.3      setosa
20            5.1          3.8           1.5          0.3      setosa
21            5.4          3.4           1.7          0.2      setosa
22            5.1          3.7           1.5          0.4      setosa
23            4.6          3.6           1.0          0.2      setosa
24            5.1          3.3           1.7          0.5      setosa
25            4.8          3.4           1.9          0.2      setosa
26            5.0          3.0           1.6          0.2      setosa
27            5.0          3.4           1.6          0.4      setosa
28            5.2          3.5           1.5          0.2      setosa
29            5.2          3.4           1.4          0.2      setosa
30            4.7          3.2           1.6          0.2      setosa
31            4.8          3.1           1.6          0.2      setosa
32            5.4          3.4           1.5          0.4      setosa
33            5.2          4.1           1.5          0.1      setosa
34            5.5          4.2           1.4          0.2      setosa
35            4.9          3.1           1.5          0.2      setosa
36            5.0          3.2           1.2          0.2      setosa
37            5.5          3.5           1.3          0.2      setosa
38            4.9          3.6           1.4          0.1      setosa
39            4.4          3.0           1.3          0.2      setosa
40            5.1          3.4           1.5          0.2      setosa
41            5.0          3.5           1.3          0.3      setosa
42            4.5          2.3           1.3          0.3      setosa
43            4.4          3.2           1.3          0.2      setosa
44            5.0          3.5           1.6          0.6      setosa
45            5.1          3.8           1.9          0.4      setosa
46            4.8          3.0           1.4          0.3      setosa
47            5.1          3.8           1.6          0.2      setosa
48            4.6          3.2           1.4          0.2      setosa
49            5.3          3.7           1.5          0.2      setosa
50            5.0          3.3           1.4          0.2      setosa
51            7.0          3.2           4.7          1.4  versicolor
52            6.4          3.2           4.5          1.5  versicolor
53            6.9          3.1           4.9          1.5  versicolor
54            5.5          2.3           4.0          1.3  versicolor
55            6.5          2.8           4.6          1.5  versicolor
56            5.7          2.8           4.5          1.3  versicolor
57            6.3          3.3           4.7          1.6  versicolor
58            4.9          2.4           3.3          1.0  versicolor
59            6.6          2.9           4.6          1.3  versicolor
60            5.2          2.7           3.9          1.4  versicolor
61            5.0          2.0           3.5          1.0  versicolor
62            5.9          3.0           4.2          1.5  versicolor
63            6.0          2.2           4.0          1.0  versicolor
64            6.1          2.9           4.7          1.4  versicolor
65            5.6          2.9           3.6          1.3  versicolor
66            6.7          3.1           4.4          1.4  versicolor
67            5.6          3.0           4.5          1.5  versicolor
68            5.8          2.7           4.1          1.0  versicolor
69            6.2          2.2           4.5          1.5  versicolor
70            5.6          2.5           3.9          1.1  versicolor
71            5.9          3.2           4.8          1.8  versicolor
72            6.1          2.8           4.0          1.3  versicolor
73            6.3          2.5           4.9          1.5  versicolor
74            6.1          2.8           4.7          1.2  versicolor
75            6.4          2.9           4.3          1.3  versicolor
76            6.6          3.0           4.4          1.4  versicolor
77            6.8          2.8           4.8          1.4  versicolor
78            6.7          3.0           5.0          1.7  versicolor
79            6.0          2.9           4.5          1.5  versicolor
80            5.7          2.6           3.5          1.0  versicolor
81            5.5          2.4           3.8          1.1  versicolor
82            5.5          2.4           3.7          1.0  versicolor
83            5.8          2.7           3.9          1.2  versicolor
84            6.0          2.7           5.1          1.6  versicolor
85            5.4          3.0           4.5          1.5  versicolor
86            6.0          3.4           4.5          1.6  versicolor
87            6.7          3.1           4.7          1.5  versicolor
88            6.3          2.3           4.4          1.3  versicolor
89            5.6          3.0           4.1          1.3  versicolor
90            5.5          2.5           4.0          1.3  versicolor
91            5.5          2.6           4.4          1.2  versicolor
92            6.1          3.0           4.6          1.4  versicolor
93            5.8          2.6           4.0          1.2  versicolor
94            5.0          2.3           3.3          1.0  versicolor
95            5.6          2.7           4.2          1.3  versicolor
96            5.7          3.0           4.2          1.2  versicolor
97            5.7          2.9           4.2          1.3  versicolor
98            6.2          2.9           4.3          1.3  versicolor
99            5.1          2.5           3.0          1.1  versicolor
100           5.7          2.8           4.1          1.3  versicolor
101           6.3          3.3           6.0          2.5   virginica
102           5.8          2.7           5.1          1.9   virginica
103           7.1          3.0           5.9          2.1   virginica
104           6.3          2.9           5.6          1.8   virginica
105           6.5          3.0           5.8          2.2   virginica
106           7.6          3.0           6.6          2.1   virginica
107           4.9          2.5           4.5          1.7   virginica
108           7.3          2.9           6.3          1.8   virginica
109           6.7          2.5           5.8          1.8   virginica
110           7.2          3.6           6.1          2.5   virginica
111           6.5          3.2           5.1          2.0   virginica
112           6.4          2.7           5.3          1.9   virginica
113           6.8          3.0           5.5          2.1   virginica
114           5.7          2.5           5.0          2.0   virginica
115           5.8          2.8           5.1          2.4   virginica
116           6.4          3.2           5.3          2.3   virginica
117           6.5          3.0           5.5          1.8   virginica
118           7.7          3.8           6.7          2.2   virginica
119           7.7          2.6           6.9          2.3   virginica
120           6.0          2.2           5.0          1.5   virginica
121           6.9          3.2           5.7          2.3   virginica
122           5.6          2.8           4.9          2.0   virginica
123           7.7          2.8           6.7          2.0   virginica
124           6.3          2.7           4.9          1.8   virginica
125           6.7          3.3           5.7          2.1   virginica
126           7.2          3.2           6.0          1.8   virginica
127           6.2          2.8           4.8          1.8   virginica
128           6.1          3.0           4.9          1.8   virginica
129           6.4          2.8           5.6          2.1   virginica
130           7.2          3.0           5.8          1.6   virginica
131           7.4          2.8           6.1          1.9   virginica
132           7.9          3.8           6.4          2.0   virginica
133           6.4          2.8           5.6          2.2   virginica
134           6.3          2.8           5.1          1.5   virginica
135           6.1          2.6           5.6          1.4   virginica
136           7.7          3.0           6.1          2.3   virginica
137           6.3          3.4           5.6          2.4   virginica
138           6.4          3.1           5.5          1.8   virginica
139           6.0          3.0           4.8          1.8   virginica
140           6.9          3.1           5.4          2.1   virginica
141           6.7          3.1           5.6          2.4   virginica
142           6.9          3.1           5.1          2.3   virginica
143           5.8          2.7           5.1          1.9   virginica
144           6.8          3.2           5.9          2.3   virginica
145           6.7          3.3           5.7          2.5   virginica
146           6.7          3.0           5.2          2.3   virginica
147           6.3          2.5           5.0          1.9   virginica
148           6.5          3.0           5.2          2.0   virginica
149           6.2          3.4           5.4          2.3   virginica
150           5.9          3.0           5.1          1.8   virginica

print the first 3 rows

In [5]:
df_iris.head(3)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa

print the number of rows and columns (shape)

In [6]:
df_iris.shape

(150, 5)

print the column names

In [7]:
for col in df_iris.columns:
    print(col)

Sepal.Length
Sepal.Width
Petal.Length
Petal.Width
Species

print the data type of each column

In [8]:
for col in df_iris.columns:
    print(df_iris.columns.dtype)

object
object
object
object
object

print the summary statistics for each of the numeric variables

In [9]:
df_iris.describe()

       Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

Read the data from this google sheet into a dataframe, df_google

https://docs.google.com/spreadsheets/d/1Uhtml8KY19LILuZsrDtlsHHDC9wuDGUSe8LTEwvdI5g/edit#gid=341089357

In [10]:
import pandas as pd

In [11]:
google_sheet_url = 'https://docs.google.com/spreadsheets/d/1Uhtml8KY19LILuZsrDtlsHHDC9wuDGUSe8LTEwvdI5g/edit#gid=341089357'

In [12]:
csv_export_url = google_sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')

In [13]:
df_google_sheet = pd.read_csv(csv_export_url)

df_google_sheet

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

print the first 3 rows

In [14]:
df_google_sheet.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

print the number of rows and columns

In [15]:
df_google_sheet.shape

(891, 12)

print the column names

In [16]:
for col in df_google_sheet.columns:
    print(col)

PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked

print the data type of each column

In [17]:
for col in df_google_sheet.columns:
    print(df_google_sheet.columns.dtype)

object
object
object
object
object
object
object
object
object
object
object
object

print the summary statistics for each of the numeric variables

In [18]:
df_google_sheet.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

print the unique values for each of your categorical variables

In [19]:
for col in df_google_sheet.columns:
    print(df_google_sheet.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

Download the previous exercise's file into an excel (File → Download → Microsoft Excel). Read the downloaded file into a dataframe named df_excel

In [20]:

df_excel = pd.read_csv('train - train.csv')

assign the first 100 rows to a new dataframe, df_excel_sample

In [21]:
df_excel_sample = df_excel.head(100)

print the number of rows of your original dataframe

In [22]:
df_excel.shape

(891, 12)

print the first 5 column names

In [23]:
print(df_excel.columns.values[:5])

['PassengerId' 'Survived' 'Pclass' 'Name' 'Sex']

print the column names that have a data type of object

In [24]:
print(df_excel.select_dtypes(include='object').columns)

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

compute the range for each of the numeric variables.

In [25]:
df_excel_nums = df_excel.select_dtypes(include='number').columns

df_excel_nums

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [26]:
ranges = df_excel[df_excel_nums].max() - df_excel[df_excel_nums].min()

ranges

PassengerId    890.0000
Survived         1.0000
Pclass           2.0000
Age             79.5800
SibSp            8.0000
Parch            6.0000
Fare           512.3292
dtype: float64

# Data Prep
# Using the Iris Data:
Use the function defined in acquire.py to load the iris data.

In [27]:
from acquire import get_iris_data

In [28]:
iris = get_iris_data()

In [29]:
iris.head()

,Unnamed: 0,species_id,species_name,measurement_id,sepal_length,sepal_width,petal_length,petal_width
0,0,1,setosa,1,5.1,3.5,1.4,0.2
1,1,1,setosa,2,4.9,3.0,1.4,0.2
2,2,1,setosa,3,4.7,3.2,1.3,0.2
3,3,1,setosa,4,4.6,3.1,1.5,0.2
4,4,1,setosa,5,5.0,3.6,1.4,0.2

Drop the species_id and measurement_id columns

In [30]:
iris = iris.drop(columns=['species_id','measurement_id'])

In [31]:
iris

,Unnamed: 0,species_name,sepal_length,sepal_width,petal_length,petal_width
0,0,setosa,5.1,3.5,1.4,0.2
1,1,setosa,4.9,3.0,1.4,0.2
2,2,setosa,4.7,3.2,1.3,0.2
3,3,setosa,4.6,3.1,1.5,0.2
4,4,setosa,5.0,3.6,1.4,0.2
5,5,setosa,5.4,3.9,1.7,0.4
6,6,setosa,4.6,3.4,1.4,0.3
7,7,setosa,5.0,3.4,1.5,0.2
8,8,setosa,4.4,2.9,1.4,0.2
9,9,setosa,4.9,3.1,1.5,0.1
10,10,setosa,5.4,3.7,1.5,0.2
11,11,setosa,4.8,3.4,1.6,0.2
12,12,setosa,4.8,3.0,1.4,0.1
13,13,setosa,4.3,3.0,1.1,0.1
14,14,setosa,5.8,4.0,1.2,0.2
15,15,setosa,5.7,4.4,1.5,0.4
16,16,setosa,5.4,3.9,1.3,0.4
17,17,setosa,5.1,3.5,1.4,0.3
18,18,setosa,5.7,3.8,1.7,0.3
19,19,setosa,5.1,3.8,1.5,0.3
20,20,setosa,5.4,3.4,1.7,0.2
21,21,setosa,5.1,3.7,1.5,0.4
22,22,setosa,4.6,3.6,1.0,0.2
23,23,setosa,5.1,3.3,1.7,0.5
24,24,setosa,4.8,3.4,1.9,0.2
25,25,setosa,5.0,3.0,1.6,0.2
26,26,setosa,5.0,3.4,1.6,0.4
27,27,setosa,5.2,3.5,1.5,0.2
28,28,setosa,5.2,3.4,1.4,0.2
29,29,setosa,4.7,3.2,1.6,0.2
30,30,setosa,4.8,3.1,1.6,0.2
31,31,setosa,5.4,3.4,1.5,0.4
32,32,setosa,5.2,4.1,1.5,0.1
33,33,setosa,5.5,4.2,1.4,0.2
34,34,setosa,4.9,3.1,1.5,0.2
35,35,setosa,5.0,3.2,1.2,0.2
36,36,setosa,5.5,3.5,1.3,0.2
37,37,setosa,4.9,3.6,1.4,0.1
38,38,setosa,4.4,3.0,1.3,0.2
39,39,setosa,5.1,3.4,1.5,0.2
40,40,setosa,5.0,3.5,1.3,0.3
41,41,setosa,4.5,2.3,1.3,0.3
42,42,setosa,4.4,3.2,1.3,0.2
43,43,setosa,5.0,3.5,1.6,0.6
44,44,setosa,5.1,3.8,1.9,0.4
45,45,setosa,4.8,3.0,1.4,0.3
46,46,setosa,5.1,3.8,1.6,0.2
47,47,setosa,4.6,3.2,1.4,0.2
48,48,setosa,5.3,3.7,1.5,0.2
49,49,setosa,5.0,3.3,1.4,0.2
50,50,versicolor,7.0,3.2,4.7,1.4
51,51,versicolor,6.4,3.2,4.5,1.5
52,52,versicolor,6.9,3.1,4.9,1.5
53,53,versicolor,5.5,2.3,4.0,1.3
54,54,versicolor,6.5,2.8,4.6,1.5
55,55,versicolor,5.7,2.8,4.5,1.3
56,56,versicolor,6.3,3.3,4.7,1.6
57,57,versicolor,4.9,2.4,3.3,1.0
58,58,versicolor,6.6,2.9,4.6,1.3
59,59,versicolor,5.2,2.7,3.9,1.4
60,60,versicolor,5.0,2.0,3.5,1.0
61,61,versicolor,5.9,3.0,4.2,1.5
62,62,versicolor,6.0,2.2,4.0,1.0
63,63,versicolor,6.1,2.9,4.7,1.4
64,64,versicolor,5.6,2.9,3.6,1.3
65,65,versicolor,6.7,3.1,4.4,1.4
66,66,versicolor,5.6,3.0,4.5,1.5
67,67,versicolor,5.8,2.7,4.1,1.0
68,68,versicolor,6.2,2.2,4.5,1.5
69,69,versicolor,5.6,2.5,3.9,1.1
70,70,versicolor,5.9,3.2,4.8,1.8
71,71,versicolor,6.1,2.8,4.0,1.3
72,72,versicolor,6.3,2.5,4.9,1.5
73,73,versicolor,6.1,2.8,4.7,1.2
74,74,versicolor,6.4,2.9,4.3,1.3
75,75,versicolor,6.6,3.0,4.4,1.4
76,76,versicolor,6.8,2.8,4.8,1.4
77,77,versicolor,6.7,3.0,5.0,1.7
78,78,versicolor,6.0,2.9,4.5,1.5
79,79,versicolor,5.7,2.6,3.5,1.0
80,80,versicolor,5.5,2.4,3.8,1.1
81,81,versicolor,5.5,2.4,3.7,1.0
82,82,versicolor,5.8,2.7,3.9,1.2
83,83,versicolor,6.0,2.7,5.1,1.6
84,84,versicolor,5.4,3.0,4.5,1.5
85,85,versicolor,6.0,3.4,4.5,1.6
86,86,versicolor,6.7,3.1,4.7,1.5
87,87,versicolor,6.3,2.3,4.4,1.3
88,88,versicolor,5.6,3.0,4.1,1.3
89,89,versicolor,5.5,2.5,4.0,1.3
90,90,versicolor,5.5,2.6,4.4,1.2
91,91,versicolor,6.1,3.0,4.6,1.4
92,92,versicolor,5.8,2.6,4.0,1.2
93,93,versicolor,5.0,2.3,3.3,1.0
94,94,versicolor,5.6,2.7,4.2,1.3
95,95,versicolor,5.7,3.0,4.2,1.2
96,96,versicolor,5.7,2.9,4.2,1.3
97,97,versicolor,6.2,2.9,4.3,1.3
98,98,versicolor,5.1,2.5,3.0,1.1
99,99,versicolor,5.7,2.8,4.1,1.3
100,100,virginica,6.3,3.3,6.0,2.5
101,101,virginica,5.8,2.7,5.1,1.9
102,102,virginica,7.1,3.0,5.9,2.1
103,103,virginica,6.3,2.9,5.6,1.8
104,104,virginica,6.5,3.0,5.8,2.2
105,105,virginica,7.6,3.0,6.6,2.1
106,106,virginica,4.9,2.5,4.5,1.7
107,107,virginica,7.3,2.9,6.3,1.8
108,108,virginica,6.7,2.5,5.8,1.8
109,109,virginica,7.2,3.6,6.1,2.5
110,110,virginica,6.5,3.2,5.1,2.0
111,111,virginica,6.4,2.7,5.3,1.9
112,112,virginica,6.8,3.0,5.5,2.1
113,113,virginica,5.7,2.5,5.0,2.0
114,114,virginica,5.8,2.8,5.1,2.4
115,115,virginica,6.4,3.2,5.3,2.3
116,116,virginica,6.5,3.0,5.5,1.8
117,117,virginica,7.7,3.8,6.7,2.2
118,118,virginica,7.7,2.6,6.9,2.3
119,119,virginica,6.0,2.2,5.0,1.5
120,120,virginica,6.9,3.2,5.7,2.3
121,121,virginica,5.6,2.8,4.9,2.0
122,122,virginica,7.7,2.8,6.7,2.0
123,123,virginica,6.3,2.7,4.9,1.8
124,124,virginica,6.7,3.3,5.7,2.1
125,125,virginica,7.2,3.2,6.0,1.8
126,126,virginica,6.2,2.8,4.8,1.8
127,127,virginica,6.1,3.0,4.9,1.8
128,128,virginica,6.4,2.8,5.6,2.1
129,129,virginica,7.2,3.0,5.8,1.6
130,130,virginica,7.4,2.8,6.1,1.9
131,131,virginica,7.9,3.8,6.4,2.0
132,132,virginica,6.4,2.8,5.6,2.2
133,133,virginica,6.3,2.8,5.1,1.5
134,134,virginica,6.1,2.6,5.6,1.4
135,135,virginica,7.7,3.0,6.1,2.3
136,136,virginica,6.3,3.4,5.6,2.4
137,137,virginica,6.4,3.1,5.5,1.8
138,138,virginica,6.0,3.0,4.8,1.8
139,139,virginica,6.9,3.1,5.4,2.1
140,140,virginica,6.7,3.1,5.6,2.4
141,141,virginica,6.9,3.1,5.1,2.3
142,142,virginica,5.8,2.7,5.1,1.9
143,143,virginica,6.8,3.2,5.9,2.3
144,144,virginica,6.7,3.3,5.7,2.5
145,145,virginica,6.7,3.0,5.2,2.3
146,146,virginica,6.3,2.5,5.0,1.9
147,147,virginica,6.5,3.0,5.2,2.0
148,148,virginica,6.2,3.4,5.4,2.3
149,149,virginica,5.9,3.0,5.1,1.8

Rename the species_name column to just species

In [32]:
iris = iris.rename(columns= {'species_name':'species'})
iris

,Unnamed: 0,species,sepal_length,sepal_width,petal_length,petal_width
0,0,setosa,5.1,3.5,1.4,0.2
1,1,setosa,4.9,3.0,1.4,0.2
2,2,setosa,4.7,3.2,1.3,0.2
3,3,setosa,4.6,3.1,1.5,0.2
4,4,setosa,5.0,3.6,1.4,0.2
5,5,setosa,5.4,3.9,1.7,0.4
6,6,setosa,4.6,3.4,1.4,0.3
7,7,setosa,5.0,3.4,1.5,0.2
8,8,setosa,4.4,2.9,1.4,0.2
9,9,setosa,4.9,3.1,1.5,0.1
10,10,setosa,5.4,3.7,1.5,0.2
11,11,setosa,4.8,3.4,1.6,0.2
12,12,setosa,4.8,3.0,1.4,0.1
13,13,setosa,4.3,3.0,1.1,0.1
14,14,setosa,5.8,4.0,1.2,0.2
15,15,setosa,5.7,4.4,1.5,0.4
16,16,setosa,5.4,3.9,1.3,0.4
17,17,setosa,5.1,3.5,1.4,0.3
18,18,setosa,5.7,3.8,1.7,0.3
19,19,setosa,5.1,3.8,1.5,0.3
20,20,setosa,5.4,3.4,1.7,0.2
21,21,setosa,5.1,3.7,1.5,0.4
22,22,setosa,4.6,3.6,1.0,0.2
23,23,setosa,5.1,3.3,1.7,0.5
24,24,setosa,4.8,3.4,1.9,0.2
25,25,setosa,5.0,3.0,1.6,0.2
26,26,setosa,5.0,3.4,1.6,0.4
27,27,setosa,5.2,3.5,1.5,0.2
28,28,setosa,5.2,3.4,1.4,0.2
29,29,setosa,4.7,3.2,1.6,0.2
30,30,setosa,4.8,3.1,1.6,0.2
31,31,setosa,5.4,3.4,1.5,0.4
32,32,setosa,5.2,4.1,1.5,0.1
33,33,setosa,5.5,4.2,1.4,0.2
34,34,setosa,4.9,3.1,1.5,0.2
35,35,setosa,5.0,3.2,1.2,0.2
36,36,setosa,5.5,3.5,1.3,0.2
37,37,setosa,4.9,3.6,1.4,0.1
38,38,setosa,4.4,3.0,1.3,0.2
39,39,setosa,5.1,3.4,1.5,0.2
40,40,setosa,5.0,3.5,1.3,0.3
41,41,setosa,4.5,2.3,1.3,0.3
42,42,setosa,4.4,3.2,1.3,0.2
43,43,setosa,5.0,3.5,1.6,0.6
44,44,setosa,5.1,3.8,1.9,0.4
45,45,setosa,4.8,3.0,1.4,0.3
46,46,setosa,5.1,3.8,1.6,0.2
47,47,setosa,4.6,3.2,1.4,0.2
48,48,setosa,5.3,3.7,1.5,0.2
49,49,setosa,5.0,3.3,1.4,0.2
50,50,versicolor,7.0,3.2,4.7,1.4
51,51,versicolor,6.4,3.2,4.5,1.5
52,52,versicolor,6.9,3.1,4.9,1.5
53,53,versicolor,5.5,2.3,4.0,1.3
54,54,versicolor,6.5,2.8,4.6,1.5
55,55,versicolor,5.7,2.8,4.5,1.3
56,56,versicolor,6.3,3.3,4.7,1.6
57,57,versicolor,4.9,2.4,3.3,1.0
58,58,versicolor,6.6,2.9,4.6,1.3
59,59,versicolor,5.2,2.7,3.9,1.4
60,60,versicolor,5.0,2.0,3.5,1.0
61,61,versicolor,5.9,3.0,4.2,1.5
62,62,versicolor,6.0,2.2,4.0,1.0
63,63,versicolor,6.1,2.9,4.7,1.4
64,64,versicolor,5.6,2.9,3.6,1.3
65,65,versicolor,6.7,3.1,4.4,1.4
66,66,versicolor,5.6,3.0,4.5,1.5
67,67,versicolor,5.8,2.7,4.1,1.0
68,68,versicolor,6.2,2.2,4.5,1.5
69,69,versicolor,5.6,2.5,3.9,1.1
70,70,versicolor,5.9,3.2,4.8,1.8
71,71,versicolor,6.1,2.8,4.0,1.3
72,72,versicolor,6.3,2.5,4.9,1.5
73,73,versicolor,6.1,2.8,4.7,1.2
74,74,versicolor,6.4,2.9,4.3,1.3
75,75,versicolor,6.6,3.0,4.4,1.4
76,76,versicolor,6.8,2.8,4.8,1.4
77,77,versicolor,6.7,3.0,5.0,1.7
78,78,versicolor,6.0,2.9,4.5,1.5
79,79,versicolor,5.7,2.6,3.5,1.0
80,80,versicolor,5.5,2.4,3.8,1.1
81,81,versicolor,5.5,2.4,3.7,1.0
82,82,versicolor,5.8,2.7,3.9,1.2
83,83,versicolor,6.0,2.7,5.1,1.6
84,84,versicolor,5.4,3.0,4.5,1.5
85,85,versicolor,6.0,3.4,4.5,1.6
86,86,versicolor,6.7,3.1,4.7,1.5
87,87,versicolor,6.3,2.3,4.4,1.3
88,88,versicolor,5.6,3.0,4.1,1.3
89,89,versicolor,5.5,2.5,4.0,1.3
90,90,versicolor,5.5,2.6,4.4,1.2
91,91,versicolor,6.1,3.0,4.6,1.4
92,92,versicolor,5.8,2.6,4.0,1.2
93,93,versicolor,5.0,2.3,3.3,1.0
94,94,versicolor,5.6,2.7,4.2,1.3
95,95,versicolor,5.7,3.0,4.2,1.2
96,96,versicolor,5.7,2.9,4.2,1.3
97,97,versicolor,6.2,2.9,4.3,1.3
98,98,versicolor,5.1,2.5,3.0,1.1
99,99,versicolor,5.7,2.8,4.1,1.3
100,100,virginica,6.3,3.3,6.0,2.5
101,101,virginica,5.8,2.7,5.1,1.9
102,102,virginica,7.1,3.0,5.9,2.1
103,103,virginica,6.3,2.9,5.6,1.8
104,104,virginica,6.5,3.0,5.8,2.2
105,105,virginica,7.6,3.0,6.6,2.1
106,106,virginica,4.9,2.5,4.5,1.7
107,107,virginica,7.3,2.9,6.3,1.8
108,108,virginica,6.7,2.5,5.8,1.8
109,109,virginica,7.2,3.6,6.1,2.5
110,110,virginica,6.5,3.2,5.1,2.0
111,111,virginica,6.4,2.7,5.3,1.9
112,112,virginica,6.8,3.0,5.5,2.1
113,113,virginica,5.7,2.5,5.0,2.0
114,114,virginica,5.8,2.8,5.1,2.4
115,115,virginica,6.4,3.2,5.3,2.3
116,116,virginica,6.5,3.0,5.5,1.8
117,117,virginica,7.7,3.8,6.7,2.2
118,118,virginica,7.7,2.6,6.9,2.3
119,119,virginica,6.0,2.2,5.0,1.5
120,120,virginica,6.9,3.2,5.7,2.3
121,121,virginica,5.6,2.8,4.9,2.0
122,122,virginica,7.7,2.8,6.7,2.0
123,123,virginica,6.3,2.7,4.9,1.8
124,124,virginica,6.7,3.3,5.7,2.1
125,125,virginica,7.2,3.2,6.0,1.8
126,126,virginica,6.2,2.8,4.8,1.8
127,127,virginica,6.1,3.0,4.9,1.8
128,128,virginica,6.4,2.8,5.6,2.1
129,129,virginica,7.2,3.0,5.8,1.6
130,130,virginica,7.4,2.8,6.1,1.9
131,131,virginica,7.9,3.8,6.4,2.0
132,132,virginica,6.4,2.8,5.6,2.2
133,133,virginica,6.3,2.8,5.1,1.5
134,134,virginica,6.1,2.6,5.6,1.4
135,135,virginica,7.7,3.0,6.1,2.3
136,136,virginica,6.3,3.4,5.6,2.4
137,137,virginica,6.4,3.1,5.5,1.8
138,138,virginica,6.0,3.0,4.8,1.8
139,139,virginica,6.9,3.1,5.4,2.1
140,140,virginica,6.7,3.1,5.6,2.4
141,141,virginica,6.9,3.1,5.1,2.3
142,142,virginica,5.8,2.7,5.1,1.9
143,143,virginica,6.8,3.2,5.9,2.3
144,144,virginica,6.7,3.3,5.7,2.5
145,145,virginica,6.7,3.0,5.2,2.3
146,146,virginica,6.3,2.5,5.0,1.9
147,147,virginica,6.5,3.0,5.2,2.0
148,148,virginica,6.2,3.4,5.4,2.3
149,149,virginica,5.9,3.0,5.1,1.8

Create dummy variables of the species name and concatenate onto the iris dataframe. (This is for practice, we don't always have to encode the target, but if we used species as a feature, we would need to encode it).

In [33]:
#pd.get_dummies(iris)  # method 1
dummy_iris = pd.get_dummies(iris.species, drop_first=True)
dummy_iris.head()

   versicolor  virginica
0           0          0
1           0          0
2           0          0
3           0          0
4           0          0

concat onto df

In [34]:
iris = pd.concat([iris, dummy_iris], axis=1)
iris.head()

,Unnamed: 0,species,sepal_length,sepal_width,petal_length,petal_width,versicolor,virginica
0,0,setosa,5.1,3.5,1.4,0.2,0,0
1,1,setosa,4.9,3.0,1.4,0.2,0,0
2,2,setosa,4.7,3.2,1.3,0.2,0,0
3,3,setosa,4.6,3.1,1.5,0.2,0,0
4,4,setosa,5.0,3.6,1.4,0.2,0,0

Create a function named prep_iris that accepts the untransformed iris data, and returns the data with the transformations above applied.

In [35]:
def prep_iris():
    iris = get_iris_data()
    iris = iris.drop(columns=['species_id','measurement_id','Unnamed: 0'])
    iris = iris.rename(columns= {'species_name':'species'})
    dummy_iris = pd.get_dummies(iris.species, drop_first=True)
    iris = pd.concat([iris, dummy_iris], axis=1)
    return iris

In [36]:
prep_iris()

,species,sepal_length,sepal_width,petal_length,petal_width,versicolor,virginica
0,setosa,5.1,3.5,1.4,0.2,0,0
1,setosa,4.9,3.0,1.4,0.2,0,0
2,setosa,4.7,3.2,1.3,0.2,0,0
3,setosa,4.6,3.1,1.5,0.2,0,0
4,setosa,5.0,3.6,1.4,0.2,0,0
5,setosa,5.4,3.9,1.7,0.4,0,0
6,setosa,4.6,3.4,1.4,0.3,0,0
7,setosa,5.0,3.4,1.5,0.2,0,0
8,setosa,4.4,2.9,1.4,0.2,0,0
9,setosa,4.9,3.1,1.5,0.1,0,0
10,setosa,5.4,3.7,1.5,0.2,0,0
11,setosa,4.8,3.4,1.6,0.2,0,0
12,setosa,4.8,3.0,1.4,0.1,0,0
13,setosa,4.3,3.0,1.1,0.1,0,0
14,setosa,5.8,4.0,1.2,0.2,0,0
15,setosa,5.7,4.4,1.5,0.4,0,0
16,setosa,5.4,3.9,1.3,0.4,0,0
17,setosa,5.1,3.5,1.4,0.3,0,0
18,setosa,5.7,3.8,1.7,0.3,0,0
19,setosa,5.1,3.8,1.5,0.3,0,0
20,setosa,5.4,3.4,1.7,0.2,0,0
21,setosa,5.1,3.7,1.5,0.4,0,0
22,setosa,4.6,3.6,1.0,0.2,0,0
23,setosa,5.1,3.3,1.7,0.5,0,0
24,setosa,4.8,3.4,1.9,0.2,0,0
25,setosa,5.0,3.0,1.6,0.2,0,0
26,setosa,5.0,3.4,1.6,0.4,0,0
27,setosa,5.2,3.5,1.5,0.2,0,0
28,setosa,5.2,3.4,1.4,0.2,0,0
29,setosa,4.7,3.2,1.6,0.2,0,0
30,setosa,4.8,3.1,1.6,0.2,0,0
31,setosa,5.4,3.4,1.5,0.4,0,0
32,setosa,5.2,4.1,1.5,0.1,0,0
33,setosa,5.5,4.2,1.4,0.2,0,0
34,setosa,4.9,3.1,1.5,0.2,0,0
35,setosa,5.0,3.2,1.2,0.2,0,0
36,setosa,5.5,3.5,1.3,0.2,0,0
37,setosa,4.9,3.6,1.4,0.1,0,0
38,setosa,4.4,3.0,1.3,0.2,0,0
39,setosa,5.1,3.4,1.5,0.2,0,0
40,setosa,5.0,3.5,1.3,0.3,0,0
41,setosa,4.5,2.3,1.3,0.3,0,0
42,setosa,4.4,3.2,1.3,0.2,0,0
43,setosa,5.0,3.5,1.6,0.6,0,0
44,setosa,5.1,3.8,1.9,0.4,0,0
45,setosa,4.8,3.0,1.4,0.3,0,0
46,setosa,5.1,3.8,1.6,0.2,0,0
47,setosa,4.6,3.2,1.4,0.2,0,0
48,setosa,5.3,3.7,1.5,0.2,0,0
49,setosa,5.0,3.3,1.4,0.2,0,0
50,versicolor,7.0,3.2,4.7,1.4,1,0
51,versicolor,6.4,3.2,4.5,1.5,1,0
52,versicolor,6.9,3.1,4.9,1.5,1,0
53,versicolor,5.5,2.3,4.0,1.3,1,0
54,versicolor,6.5,2.8,4.6,1.5,1,0
55,versicolor,5.7,2.8,4.5,1.3,1,0
56,versicolor,6.3,3.3,4.7,1.6,1,0
57,versicolor,4.9,2.4,3.3,1.0,1,0
58,versicolor,6.6,2.9,4.6,1.3,1,0
59,versicolor,5.2,2.7,3.9,1.4,1,0
60,versicolor,5.0,2.0,3.5,1.0,1,0
61,versicolor,5.9,3.0,4.2,1.5,1,0
62,versicolor,6.0,2.2,4.0,1.0,1,0
63,versicolor,6.1,2.9,4.7,1.4,1,0
64,versicolor,5.6,2.9,3.6,1.3,1,0
65,versicolor,6.7,3.1,4.4,1.4,1,0
66,versicolor,5.6,3.0,4.5,1.5,1,0
67,versicolor,5.8,2.7,4.1,1.0,1,0
68,versicolor,6.2,2.2,4.5,1.5,1,0
69,versicolor,5.6,2.5,3.9,1.1,1,0
70,versicolor,5.9,3.2,4.8,1.8,1,0
71,versicolor,6.1,2.8,4.0,1.3,1,0
72,versicolor,6.3,2.5,4.9,1.5,1,0
73,versicolor,6.1,2.8,4.7,1.2,1,0
74,versicolor,6.4,2.9,4.3,1.3,1,0
75,versicolor,6.6,3.0,4.4,1.4,1,0
76,versicolor,6.8,2.8,4.8,1.4,1,0
77,versicolor,6.7,3.0,5.0,1.7,1,0
78,versicolor,6.0,2.9,4.5,1.5,1,0
79,versicolor,5.7,2.6,3.5,1.0,1,0
80,versicolor,5.5,2.4,3.8,1.1,1,0
81,versicolor,5.5,2.4,3.7,1.0,1,0
82,versicolor,5.8,2.7,3.9,1.2,1,0
83,versicolor,6.0,2.7,5.1,1.6,1,0
84,versicolor,5.4,3.0,4.5,1.5,1,0
85,versicolor,6.0,3.4,4.5,1.6,1,0
86,versicolor,6.7,3.1,4.7,1.5,1,0
87,versicolor,6.3,2.3,4.4,1.3,1,0
88,versicolor,5.6,3.0,4.1,1.3,1,0
89,versicolor,5.5,2.5,4.0,1.3,1,0
90,versicolor,5.5,2.6,4.4,1.2,1,0
91,versicolor,6.1,3.0,4.6,1.4,1,0
92,versicolor,5.8,2.6,4.0,1.2,1,0
93,versicolor,5.0,2.3,3.3,1.0,1,0
94,versicolor,5.6,2.7,4.2,1.3,1,0
95,versicolor,5.7,3.0,4.2,1.2,1,0
96,versicolor,5.7,2.9,4.2,1.3,1,0
97,versicolor,6.2,2.9,4.3,1.3,1,0
98,versicolor,5.1,2.5,3.0,1.1,1,0
99,versicolor,5.7,2.8,4.1,1.3,1,0
100,virginica,6.3,3.3,6.0,2.5,0,1
101,virginica,5.8,2.7,5.1,1.9,0,1
102,virginica,7.1,3.0,5.9,2.1,0,1
103,virginica,6.3,2.9,5.6,1.8,0,1
104,virginica,6.5,3.0,5.8,2.2,0,1
105,virginica,7.6,3.0,6.6,2.1,0,1
106,virginica,4.9,2.5,4.5,1.7,0,1
107,virginica,7.3,2.9,6.3,1.8,0,1
108,virginica,6.7,2.5,5.8,1.8,0,1
109,virginica,7.2,3.6,6.1,2.5,0,1
110,virginica,6.5,3.2,5.1,2.0,0,1
111,virginica,6.4,2.7,5.3,1.9,0,1
112,virginica,6.8,3.0,5.5,2.1,0,1
113,virginica,5.7,2.5,5.0,2.0,0,1
114,virginica,5.8,2.8,5.1,2.4,0,1
115,virginica,6.4,3.2,5.3,2.3,0,1
116,virginica,6.5,3.0,5.5,1.8,0,1
117,virginica,7.7,3.8,6.7,2.2,0,1
118,virginica,7.7,2.6,6.9,2.3,0,1
119,virginica,6.0,2.2,5.0,1.5,0,1
120,virginica,6.9,3.2,5.7,2.3,0,1
121,virginica,5.6,2.8,4.9,2.0,0,1
122,virginica,7.7,2.8,6.7,2.0,0,1
123,virginica,6.3,2.7,4.9,1.8,0,1
124,virginica,6.7,3.3,5.7,2.1,0,1
125,virginica,7.2,3.2,6.0,1.8,0,1
126,virginica,6.2,2.8,4.8,1.8,0,1
127,virginica,6.1,3.0,4.9,1.8,0,1
128,virginica,6.4,2.8,5.6,2.1,0,1
129,virginica,7.2,3.0,5.8,1.6,0,1
130,virginica,7.4,2.8,6.1,1.9,0,1
131,virginica,7.9,3.8,6.4,2.0,0,1
132,virginica,6.4,2.8,5.6,2.2,0,1
133,virginica,6.3,2.8,5.1,1.5,0,1
134,virginica,6.1,2.6,5.6,1.4,0,1
135,virginica,7.7,3.0,6.1,2.3,0,1
136,virginica,6.3,3.4,5.6,2.4,0,1
137,virginica,6.4,3.1,5.5,1.8,0,1
138,virginica,6.0,3.0,4.8,1.8,0,1
139,virginica,6.9,3.1,5.4,2.1,0,1
140,virginica,6.7,3.1,5.6,2.4,0,1
141,virginica,6.9,3.1,5.1,2.3,0,1
142,virginica,5.8,2.7,5.1,1.9,0,1
143,virginica,6.8,3.2,5.9,2.3,0,1
144,virginica,6.7,3.3,5.7,2.5,0,1
145,virginica,6.7,3.0,5.2,2.3,0,1
146,virginica,6.3,2.5,5.0,1.9,0,1
147,virginica,6.5,3.0,5.2,2.0,0,1
148,virginica,6.2,3.4,5.4,2.3,0,1
149,virginica,5.9,3.0,5.1,1.8,0,1

# Using the Titanic dataset

Use the function defined in acquire.py to load the Titanic data.

In [37]:
from acquire import get_titanic_data

titanic = get_titanic_data()
titanic.head()

,Unnamed: 0,passenger_id,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,deck,embark_town,alone
0,0,0,0,3,male,22.0,1,0,7.2500,S,Third,NaN,Southampton,0
1,1,1,1,1,female,38.0,1,0,71.2833,C,First,C,Cherbourg,0
2,2,2,1,3,female,26.0,0,0,7.9250,S,Third,NaN,Southampton,1
3,3,3,1,1,female,35.0,1,0,53.1000,S,First,C,Southampton,0
4,4,4,0,3,male,35.0,0,0,8.0500,S,Third,NaN,Southampton,1

Drop any unnecessary, unhelpful, or duplicated columns.

In [38]:
titanic = titanic.drop(columns=['embarked', 'class', 'age', 'deck'])
titanic.head()

,Unnamed: 0,passenger_id,survived,pclass,sex,sibsp,parch,fare,embark_town,alone
0,0,0,0,3,male,1,0,7.2500,Southampton,0
1,1,1,1,1,female,1,0,71.2833,Cherbourg,0
2,2,2,1,3,female,0,0,7.9250,Southampton,1
3,3,3,1,1,female,1,0,53.1000,Southampton,0
4,4,4,0,3,male,0,0,8.0500,Southampton,1

Encode the categorical columns. Create dummy variables of the categorical columns and concatenate them onto the dataframe.

In [39]:
tit_dummy = pd.get_dummies(data=titanic[['sex','embark_town']],drop_first=True)
tit_dummy.head()

   sex_male  embark_town_Queenstown  embark_town_Southampton
0         1                       0                        1
1         0                       0                        0
2         0                       0                        1
3         0                       0                        1
4         1                       0                        1

concat dummy to df

In [40]:
titanic = pd.concat([titanic, tit_dummy],axis=1)
titanic.head()

,Unnamed: 0,passenger_id,survived,pclass,sex,sibsp,parch,fare,embark_town,alone,sex_male,embark_town_Queenstown,embark_town_Southampton
0,0,0,0,3,male,1,0,7.2500,Southampton,0,1,0,1
1,1,1,1,1,female,1,0,71.2833,Cherbourg,0,0,0,0
2,2,2,1,3,female,0,0,7.9250,Southampton,1,0,0,1
3,3,3,1,1,female,1,0,53.1000,Southampton,0,0,0,1
4,4,4,0,3,male,0,0,8.0500,Southampton,1,1,0,1

Create a function named prep_titanic that accepts the raw titanic data, and returns the data with the transformations above applied.

In [41]:
def prep_titanic():
    titanic = get_titanic_data()
    titanic = titanic.drop(columns=['embarked', 'class', 'age', 'deck','Unnamed: 0'])
    tit_dummy = pd.get_dummies(data=titanic[['sex','embark_town']],drop_first=True)
    titanic = pd.concat([titanic, tit_dummy],axis=1)
    return titanic

In [42]:
prep_titanic()

,passenger_id,survived,pclass,sex,sibsp,parch,fare,embark_town,alone,sex_male,embark_town_Queenstown,embark_town_Southampton
0,0,0,3,male,1,0,7.2500,Southampton,0,1,0,1
1,1,1,1,female,1,0,71.2833,Cherbourg,0,0,0,0
2,2,1,3,female,0,0,7.9250,Southampton,1,0,0,1
3,3,1,1,female,1,0,53.1000,Southampton,0,0,0,1
4,4,0,3,male,0,0,8.0500,Southampton,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,0,2,male,0,0,13.0000,Southampton,1,1,0,1
887,887,1,1,female,0,0,30.0000,Southampton,1,0,0,1
888,888,0,3,female,1,2,23.4500,Southampton,0,0,0,1
889,889,1,1,male,0,0,30.0000,Cherbourg,1,1,0,0
890,890,0,3,male,0,0,7.7500,Queenstown,1,1,1,0

# Using the Telco dataset

Use the function defined in acquire.py to load the Telco data.

In [6]:
from acquire import get_telco_data

telco = get_telco_data()
telco.head()

,Unnamed: 0,payment_type_id,internet_service_type_id,contract_type_id,customer_id,gender,senior_citizen,partner,dependents,tenure,...,tech_support,streaming_tv,streaming_movies,paperless_billing,monthly_charges,total_charges,churn,contract_type,internet_service_type,payment_type
0,0,2,1,2,0002-ORFBO,Female,0,Yes,Yes,9,...,Yes,Yes,No,Yes,65.6,593.3,No,One year,DSL,Mailed check
1,1,2,1,1,0003-MKNFE,Male,0,No,No,9,...,No,No,Yes,No,59.9,542.4,No,Month-to-month,DSL,Mailed check
2,2,1,2,1,0004-TLHLJ,Male,0,No,No,4,...,No,No,No,Yes,73.9,280.85,Yes,Month-to-month,Fiber optic,Electronic check
3,3,1,2,1,0011-IGKFF,Male,1,Yes,No,13,...,No,Yes,Yes,Yes,98.0,1237.85,Yes,Month-to-month,Fiber optic,Electronic check
4,4,2,2,1,0013-EXCHZ,Female,1,Yes,No,3,...,Yes,Yes,No,Yes,83.9,267.4,Yes,Month-to-month,Fiber optic,Mailed check

Drop any unnecessary, unhelpful, or duplicated columns. This could mean dropping foreign key columns but keeping the corresponding string values, for example.

In [55]:
#telco = telco.drop_duplicates()
# using crosstab
pd.crosstab(telco.payment_type, telco.payment_type_id)

payment_type_id               1     2     3     4
payment_type
Bank transfer (automatic)     0     0  1544     0
Credit card (automatic)       0     0     0  1522
Electronic check           2365     0     0     0
Mailed check                  0  1612     0     0

In [56]:
pd.crosstab(telco.contract_type_id, telco.contract_type)

contract_type     Month-to-month  One year  Two year
contract_type_id
1                           3875         0         0
2                              0      1473         0
3                              0         0      1695

In [57]:
pd.crosstab(telco.internet_service_type, telco.internet_service_type_id)

internet_service_type_id     1     2     3
internet_service_type
DSL                       2421     0     0
Fiber optic                  0  3096     0
None                         0     0  1526

removing redudant columns

In [58]:
telco = telco.drop(columns=['internet_service_type_id','contract_type_id', 'payment_type_id'])
telco.head()

,Unnamed: 0,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,online_security,...,tech_support,streaming_tv,streaming_movies,paperless_billing,monthly_charges,total_charges,churn,contract_type,internet_service_type,payment_type
0,0,0002-ORFBO,Female,0,Yes,Yes,9,Yes,No,No,...,Yes,Yes,No,Yes,65.6,593.3,No,One year,DSL,Mailed check
1,1,0003-MKNFE,Male,0,No,No,9,Yes,Yes,No,...,No,No,Yes,No,59.9,542.4,No,Month-to-month,DSL,Mailed check
2,2,0004-TLHLJ,Male,0,No,No,4,Yes,No,No,...,No,No,No,Yes,73.9,280.85,Yes,Month-to-month,Fiber optic,Electronic check
3,3,0011-IGKFF,Male,1,Yes,No,13,Yes,No,No,...,No,Yes,Yes,Yes,98.0,1237.85,Yes,Month-to-month,Fiber optic,Electronic check
4,4,0013-EXCHZ,Female,1,Yes,No,3,Yes,No,No,...,Yes,Yes,No,Yes,83.9,267.4,Yes,Month-to-month,Fiber optic,Mailed check

Encode the categorical columns. Create dummy variables of the categorical columns and concatenate them onto the dataframe.

In [60]:
telco.select_dtypes(include='object').columns

,Unnamed: 0,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,online_security,...,tech_support,streaming_tv,streaming_movies,paperless_billing,monthly_charges,total_charges,churn,contract_type,internet_service_type,payment_type
0,0,0002-ORFBO,Female,0,Yes,Yes,9,Yes,No,No,...,Yes,Yes,No,Yes,65.60,593.3,No,One year,DSL,Mailed check
1,1,0003-MKNFE,Male,0,No,No,9,Yes,Yes,No,...,No,No,Yes,No,59.90,542.4,No,Month-to-month,DSL,Mailed check
2,2,0004-TLHLJ,Male,0,No,No,4,Yes,No,No,...,No,No,No,Yes,73.90,280.85,Yes,Month-to-month,Fiber optic,Electronic check
3,3,0011-IGKFF,Male,1,Yes,No,13,Yes,No,No,...,No,Yes,Yes,Yes,98.00,1237.85,Yes,Month-to-month,Fiber optic,Electronic check
4,4,0013-EXCHZ,Female,1,Yes,No,3,Yes,No,No,...,Yes,Yes,No,Yes,83.90,267.4,Yes,Month-to-month,Fiber optic,Mailed check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,7038,9987-LUTYD,Female,0,No,No,13,Yes,No,Yes,...,Yes,No,No,No,55.15,742.9,No,One year,DSL,Mailed check
7039,7039,9992-RRAMN,Male,0,Yes,No,22,Yes,Yes,No,...,No,No,Yes,Yes,85.10,1873.7,Yes,Month-to-month,Fiber optic,Electronic check
7040,7040,9992-UJOEL,Male,0,No,No,2,Yes,No,No,...,No,No,No,Yes,50.30,92.75,No,Month-to-month,DSL,Mailed check
7041,7041,9993-LHIEB,Male,0,Yes,Yes,67,Yes,No,Yes,...,Yes,No,Yes,No,67.85,4627.65,No,Two year,DSL,Mailed check
7042,7042,9995-HOTOH,Male,0,Yes,Yes,63,No,No phone service,Yes,...,No,Yes,Yes,No,59.00,3707.6,No,Two year,DSL,Electronic check

In [61]:
pd.get_dummies(telco[['gender','partner', 'dependents', 'phone_service','multiple_lines', 'online_security', 'online_backup',
       'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies',
       'paperless_billing', 'churn', 'contract_type',
       'internet_service_type', 'payment_type' ]], drop_first=True)

,gender_Male,partner_Yes,dependents_Yes,phone_service_Yes,multiple_lines_No phone service,multiple_lines_Yes,online_security_No internet service,online_security_Yes,online_backup_No internet service,online_backup_Yes,...,streaming_movies_Yes,paperless_billing_Yes,churn_Yes,contract_type_One year,contract_type_Two year,internet_service_type_Fiber optic,internet_service_type_None,payment_type_Credit card (automatic),payment_type_Electronic check,payment_type_Mailed check
0,0,1,1,1,0,0,0,0,0,1,...,0,1,0,1,0,0,0,0,0,1
1,1,0,0,1,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
2,1,0,0,1,0,0,0,0,0,0,...,0,1,1,0,0,1,0,0,1,0
3,1,1,0,1,0,0,0,0,0,1,...,1,1,1,0,0,1,0,0,1,0
4,0,1,0,1,0,0,0,0,0,0,...,0,1,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,0,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
7039,1,1,0,1,0,1,0,0,0,0,...,1,1,1,0,0,1,0,0,1,0
7040,1,0,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1
7041,1,1,1,1,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,1
7042,1,1,1,0,1,0,0,1,0,1,...,1,0,0,0,1,0,0,0,1,0

Create a function named prep_telco that accepts the raw telco data, and returns the data with the transformations above applied.

def prep_telco():
    telco = get_telco_data()
    #telco = telco.drop_duplicates()
    telco = telco.drop(columns=['internet_service_type_id', 'contract_type_id', 'payment_type_id'])
    telco = pd.get_dummies(telco[['gender','partner', 'dependents', 'phone_service','multiple_lines', 'online_security', 'online_backup',
       'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies',
       'paperless_billing', 'churn', 'contract_type',
       'internet_service_type', 'payment_type' ]],drop_first=True)
    return telco

new function for prep_telco below, incomplete



def prep_telco():
    telco = get_telco_data()
    telco = telco.drop(columns=['internet_service_type_id', 'contract_type_id', 'payment_type_id'])

    telco['gender_encoded'] = telco.gender.map({'Female': 1, 'Male': 0})
    telco['partner_encoded'] = telco.partner.map({'Yes': 1, 'No': 0})
    telco['dependents_encoded'] = telco.dependents.map({'Yes': 1, 'No': 0})
    telco['phone_service_encoded'] = telco.phone_service.map({'Yes': 1, 'No': 0})
    telco['paperless_billing_encoded'] = telco.paperless_billing.map({'Yes': 1, 'No': 0})
    telco['churn_encoded'] = telco.churn.map({'Yes': 1, 'No': 0})
    
    dummy_df = pd.get_dummies(telco[['multiple_lines', \
                              'online_security', \
                              'online_backup', \
                              'device_protection', \
                              'tech_support', \
                              'streaming_tv', \
                              'streaming_movies', \
                              'contract_type', \
                              'internet_service_type', \
                              'payment_type'
                            ]],
                              drop_first=True)
    telco = pd.concat( [telco, dummy_df], axis=1 )
    
    return telco

In [27]:
def prep_telco():
    telco = get_telco_data()
    telco = telco.drop(columns=['internet_service_type_id', 'contract_type_id', 'payment_type_id','Unnamed: 0'])

    telco['gender_encoded'] = telco.gender.map({'Female': 1, 'Male': 0})
    telco['partner_encoded'] = telco.partner.map({'Yes': 1, 'No': 0})
    telco['dependents_encoded'] = telco.dependents.map({'Yes': 1, 'No': 0})
    telco['phone_service_encoded'] = telco.phone_service.map({'Yes': 1, 'No': 0})
    telco['paperless_billing_encoded'] = telco.paperless_billing.map({'Yes': 1, 'No': 0})
    telco['churn_encoded'] = telco.churn.map({'Yes': 1, 'No': 0})
    
    dummy_df = pd.get_dummies(telco[['multiple_lines', \
                              'online_security', \
                              'online_backup', \
                              'device_protection', \
                              'tech_support', \
                              'streaming_tv', \
                              'streaming_movies', \
                              'contract_type', \
                              'internet_service_type', \
                              'payment_type'
                            ]],
                              drop_first=True)
    telco = pd.concat( [telco, dummy_df], axis=1 )
    
    return telco

# Split your data

Write a function to split your data into train, test and validate datasets. Add this function to prepare.py.

In [19]:
# a good data split is 60/20/20 with 60 being train

# ranges = df_excel[df_excel_nums].max() - df_excel[df_excel_nums].min()
import pandas as pd
from sklearn.model_selection import train_test_split

In [20]:


def my_train_test_split(df, target=None):
    if target:
        train, test = train_test_split(df, test_size=.2, random_state=123, stratify=df[target])
        train, validate = train_test_split(train, test_size=.25, random_state=123, stratify=train[target])
    else:
        train, test = train_test_split(df, test_size=.2, random_state=123, stratify=df[target])
        train, validate = train_test_split(train, test_size=.25, random_state=123, stratify=train[target])
    return train, validate, test

In [ ]:
target = 'species'

In [ ]:
train_iris, validate_iris, test_iris = my_train_test_split(prep_iris(), target)

In [ ]:
print('Prepared dataframe: {}'.format(prep_iris().shape))
print('Train: {}'.format(train_iris.shape))
print('Validate: {}'.format(validate_iris.shape))
print('Test: {}'.format(test_iris.shape))

for titanic

In [83]:
target = 'survived'

In [84]:
train_tit, validate_tit, test_tit = my_train_test_split(prep_titanic(), target)

In [85]:
print('Prepared dataframe: {}'.format(prep_titanic().shape))
print('Train: {}'.format(train_tit.shape))
print('Validate: {}'.format(validate_tit.shape))
print('Test: {}'.format(test_tit.shape))

Prepared dataframe: (891, 12)
Train: (534, 12)
Validate: (178, 12)
Test: (179, 12)

for telco

In [28]:
target = 'churn'

In [29]:
train_telco, validate_telco, test_telco = my_train_test_split(prep_telco(), target)

In [30]:
print('Prepared dataframe: {}'.format(prep_telco().shape))
print('Train: {}'.format(train_telco.shape))
print('Validate: {}'.format(validate_telco.shape))
print('Test: {}'.format(test_telco.shape))

Prepared dataframe: (7043, 48)
Train: (4225, 48)
Validate: (1409, 48)
Test: (1409, 48)